spring.application.name=BAN-HANG

# =========================
# DATABASE
# =========================
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# =========================
# SERVER
# =========================
server.port=${PORT:8080}

# =========================
# JWT
# =========================
banhang.jwt.validity-in-accessToken-seconds=${JWT_ACCESS_VALIDITY:6000}
banhang.jwt.validity-in-refreshToken-seconds=${JWT_REFRESH_VALIDITY:360000}

hoidanhit.jwt.base64-secret=${JWT_SECRET}
